# Site settings
title: Dynamical Systems and AI Research Group
email: vignar@sc.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "Dynamical-Systems" # the subpath of your site, e.g. /blog/
url: "sgavir8738.github.io" # the base hostname & protocol for your site

linedin_username: vignar
github_username: vigsnar

# Build settings
markdown: kramdown
